version: "3.9"
services:
  db:
    container_name: "sqlserver"
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SQLServerPassword1"
      ACCEPT_EULA: "Y"
    volumes:
      - "sqlvolume:/var/opt/mssql"
volumes:
 sqlvolume: