version: "3.4"

services:
  api:
    container_name: "shopping-bag"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DevCertsPassword1!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
  db:
    container_name: "sqlserver"
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SQLServerPassword1!"
      ACCEPT_EULA: "Y"
    volumes:
      - "sqlvolume:/var/opt/mssql"
volumes:
  sqlvolume:
